const { readFileSync, existsSync, writeFileSync } = require('fs');
const { load, dump } = require('js-yaml');
const boxen = require('boxen');
const { generateChecksum } = require('./utils');

class Lock {
  #configHash;
  #configPath;
  #path;
  #current;
  #providedData;

  constructor(path, configurationPath, configurationHash) {
    this.#path = path;
    this.configurationPath = configurationPath;
    this.configurationHash = configurationHash;
    this.#current = existsSync(path) ? load(readFileSync(path).toString(), 'utf8') : null;
  }

  set configurationPath(path) {
    this.#configPath = path;
  }

  set configurationHash(hash) {
    this.#configHash = hash;
  }

  set answers(list) {
    this.#providedData = list;
  }

  get answers() {
    return this.#providedData;
  }

  get data() {
    return {
      checksum: { file: this.#configPath, hash: this.#configHash },
      variables: this.#providedData,
    };
  }

  get isFileUpdated() {
    return (
      !this.#current ||
      !this.#current.checksum ||
      !this.#current.checksum.file ||
      !this.#current.checksum.hash ||
      this.#current.checksum.file !== this.#configPath ||
      this.#current.checksum.hash !== this.#configHash
    );
  }

  get isAnswersChanged() {
    const isCurrentExist = !!(this.#current && this.#current.variables);
    return (
      !isCurrentExist ||
      (isCurrentExist &&
        !!this.#providedData &&
        generateChecksum(this.#current.variables) !== generateChecksum(this.#providedData))
    );
  }

  restore() {
    const content = dump(this.#current);
    writeFileSync(
      this.#path,
      `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# feasible lock file

${content}`,
    );
  }

  save() {
    // console.log({ isFileUpdated: this.isFileUpdated, isAnswersChanged: this.isAnswersChanged });
    if (this.isFileUpdated || this.isAnswersChanged) {
      const content = dump(this.data);
      writeFileSync(
        this.#path,
        `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# feasible lock file

${content}`,
      );
      console.log(boxen('Lock file updated!', { borderColor: 'magenta', padding: 1 }));
      return true;
    }
    return false;
  }

  getVariableValue(name, initial, options) {
    const val =
      this.#current && this.#current.variables && name in this.#current.variables
        ? this.#current.variables[name]
        : initial;
    if (options && options.includes(val)) {
      return options.indexOf(val);
    }
    return val;
  }
}

module.exports = Lock;
