name: Test

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Generate coverage report
        run: npx c8 --reporter=text --reporter=lcov npm test
      - uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
